insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (1, 'ABIF', 'Religion', 'R', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (2, 'ABIF', 'Deutsch', 'D', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (3, 'ABIF', 'Englisch', 'E1', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (4, 'ABIF', 'Angewandte  und techn. Mathematik', 'AM', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (5, 'ABIF', 'Angewandte Informatik(Netzwerk Grundlage) gemeinsam mit 3AKIF-NVS', 'AINF', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (6, 'ABIF', 'Tech. und naturwissensch. Grundlagen (Physik)', 'NWG2', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (7, 'ABIF', 'Tech. und naturwissensch. Grundlagen (Chemie)', 'NWG2', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (8, 'ABIF', 'Grundlagen der Informatik:  (GDV  + STS + C#-Einführung)', 'GINF', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (9, 'ABIF', 'Computerpraktikum: (CPR )', 'COPR', 1); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (10, 'ABIF', 'Religion', 'R', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (11, 'ABIF', 'Deutsch', 'D', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (12, 'ABIF', 'Englisch', 'E1', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (13, 'ABIF', 'Angewandte  und techn. Mathematik', 'AM', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (14, 'ABIF', 'Angewandte Informatik(Netzwerk Grundlage) gemeinsam mit 3AKIF-NVS', 'AINF', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (15, 'ABIF', 'Tech. und naturwissensch. Grundlagen (Physik)', 'NWG2', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (16, 'ABIF', 'Tech. und naturwissensch. Grundlagen (Chemie)', 'NWG2', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (17, 'ABIF', 'Grundlagen der Informatik:  (GDV  + STS + C#-Einführung)', 'GINF', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (18, 'ABIF', 'Computerpraktikum: (CPR )', 'COPR', 2); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (19, 'ABIF', 'Religion', 'R', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (20, 'ABIF', 'Deutsch', 'D', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (21, 'ABIF', 'Englisch', 'E1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (22, 'ABIF', 'Angewandte  und techn. Mathematik', 'AM', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (23, 'ABIF', 'Programmieren und Software (C#)', 'POS1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (24, 'ABIF', 'Datenbanken und Informationssysteme', 'DBI1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (25, 'ABIF', 'Betriebswirtschaft und Management', 'BWM', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (26, 'ABIF', 'Systemplanung und Projektentwicklung', 'SYP1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (27, 'ABIF', 'Technische Informatik: Betriebssysteme ', 'TINF', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (28, 'ABIF', 'Computerpraktikum: C-Programmierung ', 'COPR', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (29, 'ABIF', 'Religion', 'R', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (30, 'ABIF', 'Deutsch', 'D', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (31, 'ABIF', 'Englisch', 'E1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (32, 'ABIF', 'Angewandte  und techn. Mathematik', 'AM', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (33, 'ABIF', 'Programmieren und Software (C#)', 'POS1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (34, 'ABIF', 'Datenbanken und Informationssysteme', 'DBI1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (35, 'ABIF', 'Betriebswirtschaft und Management', 'BWM', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (36, 'ABIF', 'Systemplanung und Projektentwicklung', 'SYP1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (37, 'ABIF', 'Technische Informatik: Betriebssysteme ', 'TINF', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (38, 'ABIF', 'Computerpraktikum: C-Programmierung ', 'COPR', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (39, 'ABIF', 'Religion', 'R', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (40, 'ABIF', 'Deutsch / Kommunikation', 'DUK', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (41, 'ABIF', 'Englisch / Kommunikation', 'EUK', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (42, 'ABIF', 'Angewandte  und techn. Mathematik', 'AM', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (43, 'ABIF', 'Wirtschaft und Recht', 'WR3', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (44, 'ABIF', 'Programmieren und Software (C#)', 'POS1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (45, 'ABIF', 'Datenbanken und Informationssysteme', 'DBI1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (46, 'ABIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (47, 'ABIF', 'Betriebswirtschaft und Management', 'BWM', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (48, 'ABIF', 'Systemplanung und Projektentwicklung', 'SYP1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (49, 'ABIF', 'Religion', 'R', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (50, 'ABIF', 'Deutsch / Kommunikation', 'D', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (51, 'ABIF', 'Englisch / Kommunikation', 'E1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (52, 'ABIF', 'Angewandte  und techn. Mathematik', 'AM', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (53, 'ABIF', 'Wirtschaft und Recht', 'WR3', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (54, 'ABIF', 'Programmieren und Software (C#)', 'POS1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (55, 'ABIF', 'Datenbanken und Informationssysteme', 'DBI1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (56, 'ABIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (57, 'ABIF', 'Betriebswirtschaft und Management', 'BWM', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (58, 'ABIF', 'Systemplanung und Projektentwicklung', 'SYP1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (59, 'ABIF', 'Wirtschaft und Recht', 'WR3', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (60, 'ABIF', 'Programmieren und Software (C#)', 'POS1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (61, 'ABIF', 'Datenbanken und Informationssysteme', 'DBI1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (62, 'ABIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (63, 'ABIF', 'Netzwrksysteme und verteilte System: verteiles Programmieren', 'NVS1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (64, 'ABIF', 'Betriebswirtschaft und Management', 'BWM', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (65, 'ABIF', 'Systemplanung und Projektentwicklung', 'SYP1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (66, 'ABIF', 'Wirtschaft und Recht', 'WR3', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (67, 'ABIF', 'Programmieren und Software (C#)', 'POS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (68, 'ABIF', 'Datenbanken und Informationssysteme', 'DBI1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (69, 'ABIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (70, 'ABIF', 'Netzwrksysteme und verteilte System: verteiles Programmieren', 'NVS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (71, 'ABIF', 'Betriebswirtschaft und Management', 'BWM', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (72, 'ABIF', 'Systemplanung und Projektentwicklung', 'SYP1', 8);

insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (73, 'AKIF', 'Religion', 'R', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (74, 'AKIF', 'Programmieren und Software (C#)', 'POS1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (75, 'AKIF', 'Datenbanken und Informationssysteme', 'DBI1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (76, 'AKIF', 'Netzwrksysteme und verteilte System: AINF - gemeinsam mit 1ABIF', 'NVS1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (77, 'AKIF', 'Betriebswirtschaft und Management', 'BWM', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (78, 'AKIF', 'Systemplanung und Projektentwicklung', 'SYP1', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (79, 'AKIF', 'Technische Informatik: GINF (Grundlagen)', 'TINF', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (80, 'AKIF', 'Technische Informatik: TINF (Betriebssysteme)', 'TINF', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (81, 'AKIF', 'Computerpraktikum: (CPR )', 'CORP', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (82, 'AKIF', 'Computerpraktikum: (C-Programmieren)', 'CORP', 3); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (83, 'AKIF', 'Religion', 'R', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (84, 'AKIF', 'Programmieren und Software (C#)', 'POS1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (85, 'AKIF', 'Datenbanken und Informationssysteme', 'DBI1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (86, 'AKIF', 'Netzwrksysteme und verteilte System: AINF - gemeinsam mit 1ABIF', 'NVS1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (87, 'AKIF', 'Betriebswirtschaft und Management', 'BWM', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (88, 'AKIF', 'Systemplanung und Projektentwicklung', 'SYP1', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (89, 'AKIF', 'Technische Informatik: GINF (Grundlagen)', 'TINF', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (90, 'AKIF', 'Technische Informatik: TINF (Betriebssysteme)', 'TINF', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (91, 'AKIF', 'Computerpraktikum: (CPR )', 'CORP', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (92, 'AKIF', 'Computerpraktikum: (C-Programmieren)', 'CORP', 4); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (93, 'AKIF', 'Religion', 'R', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (94, 'AKIF', 'Deutsch / Kommunikation', 'DUK', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (95, 'AKIF', 'Englisch / Kommunikation', 'EUK', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (96, 'AKIF', 'Angewandte  und techn. Mathematik', 'AM', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (97, 'AKIF', 'Wirtschaft und Recht', 'WR3', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (98, 'AKIF', 'Programmieren und Software (C#)', 'POS1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (99, 'AKIF', 'Datenbanken und Informationssysteme', 'DBI1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (100, 'AKIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (101, 'AKIF', 'Betriebswirtschaft und Management', 'BWM', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (102, 'AKIF', 'Systemplanung und Projektentwicklung', 'SYP1', 5); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (103, 'AKIF', 'Religion', 'R', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (104, 'AKIF', 'Angewandte  und techn. Mathematik', 'AM', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (105, 'AKIF', 'Wirtschaft und Recht', 'WR3', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (106, 'AKIF', 'Programmieren und Software (C#)', 'POS1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (107, 'AKIF', 'Datenbanken und Informationssysteme', 'DBI1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (108, 'AKIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (109, 'AKIF', 'Betriebswirtschaft und Management', 'BWM', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (110, 'AKIF', 'Systemplanung und Projektentwicklung', 'SYP1', 6); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (111, 'AKIF', 'Wirtschaft und Recht', 'WR3', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (112, 'AKIF', 'Programmieren und Software (C#)', 'POS1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (113, 'AKIF', 'Datenbanken und Informationssysteme', 'DBI1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (114, 'AKIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (115, 'AKIF', 'Netzwrksysteme und verteilte System: Java - verteiles Programmieren', 'NVS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (116, 'AKIF', 'Betriebswirtschaft und Management', 'BWM2', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (117, 'AKIF', 'Systemplanung und Projektentwicklung', 'SYP1', 7); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (118, 'AKIF', 'Wirtschaft und Recht', 'WR3', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (119, 'AKIF', 'Programmieren und Software (C#)', 'POS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (120, 'AKIF', 'Datenbanken und Informationssysteme', 'DBI1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (121, 'AKIF', 'Netzwrksysteme und verteilte System: NVS', 'NVS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (122, 'AKIF', 'Netzwrksysteme und verteilte System: Java - verteiles Programmieren', 'NVS1', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (123, 'AKIF', 'Betriebswirtschaft und Management', 'BWM2', 8); 
insert into Gegenstand(Id, Klasse, Kolleg, Fach, Sem) values (124, 'AKIF', 'Systemplanung und Projektentwicklung', 'SYP1', 8); 

insert into Schueler(id, KLasse, LastName, FirstName) values (125, '1ABIF', 'Aichmayr', 'Simon'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (126, '1ABIF', 'Brummer', 'Wolfgang'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (127, '1ABIF', 'Eisenführer', 'Josef'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (128, '1ABIF', 'Etzinger', 'Jonathan'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (129, '1ABIF', 'Flieger', 'Marcel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (130, '1ABIF', 'Florescu', 'Sorin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (131, '1ABIF', 'Gattringer', 'Dominik'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (132, '1ABIF', 'Göhring', 'Christian-Alexander'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (133, '1ABIF', 'Grasch', 'Bernhard'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (134, '1ABIF', 'Gutenbrunner', 'Michael'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (135, '1ABIF', 'Hartenthaler', 'Patrick'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (136, '1ABIF', 'Hattinger', 'Hermann'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (137, '1ABIF', 'Imamovic', 'Ajnur'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (138, '1ABIF', 'Jonke', 'Dominik'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (139, '1ABIF', 'Königshofer', 'Pascal'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (140, '1ABIF', 'Leitenmüller', 'Julia'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (141, '1ABIF', 'Lochner', 'Rene'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (142, '1ABIF', 'Mair', 'Stefan'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (143, '1ABIF', 'Neuhuber', 'Peter'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (144, '1ABIF', 'Niederwimmer', 'Rainer'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (145, '1ABIF', 'Novac', 'Denis'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (146, '1ABIF', 'Pyringer', 'Stefano'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (147, '1ABIF', 'Reichert', 'Oliver'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (148, '1ABIF', 'Stanciu', 'Dunn Constantin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (149, '1ABIF', 'Sterner', 'Marcel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (150, '1ABIF', 'Stuhlpfarrer', 'Herbert'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (151, '1ABIF', 'Thurn', 'Lukas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (152, '1ABIF', 'Torani', 'Homayon'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (153, '1ABIF', 'Unterrainer', 'Marcus'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (154, '1ABIF', 'Vrhovac', 'Mladen'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (155, '3ABIF', 'Altunkaya', 'Deniz'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (156, '3ABIF', 'Amir Riahi', 'Ramtin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (157, '3ABIF', 'Barak', 'Mustafa'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (158, '3ABIF', 'Bozbey', 'Tolga'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (159, '3ABIF', 'Eichinger', 'Maximilian'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (160, '3ABIF', 'El-Husseini', 'Mohamed'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (161, '3ABIF', 'Engleder', 'Michael'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (162, '3ABIF', 'Freudenthaler', 'Markus'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (163, '3ABIF', 'Has', 'Michael'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (164, '3ABIF', 'Hatwagner', 'Alexander'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (165, '3ABIF', 'Hlavacek', 'Martin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (166, '3ABIF', 'Huang', 'Andi'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (167, '3ABIF', 'Kühberger', 'Stefan'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (168, '3ABIF', 'Mühleder', 'Markus'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (169, '3ABIF', 'Ozegovic', 'Aleksandar'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (170, '3ABIF', 'Pangerl', 'Stefan'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (171, '3ABIF', 'Pechak', 'Martin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (172, '3ABIF', 'Rukoli', 'Daniel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (173, '3ABIF', 'Saidi', 'Said'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (174, '3ABIF', 'Seidl', 'Franz'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (175, '3ABIF', 'Trnka', 'Matthias'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (176, '3ABIF', 'Walchshofer', 'Werner'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (177, '5ABIF', 'Bauchinger', 'Jakob'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (178, '5ABIF', 'Bauernberger', 'Thomas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (179, '5ABIF', 'Biebl', 'Andreas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (180, '5ABIF', 'Brandstetter', 'Sabine'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (181, '5ABIF', 'Breitwieser', 'Martin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (182, '5ABIF', 'Derntl', 'Thomas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (183, '5ABIF', 'Hartl', 'Marco'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (184, '5ABIF', 'Höller', 'Christoph'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (185, '5ABIF', 'Holzmann', 'Christopher'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (186, '5ABIF', 'Kaiser', 'Simon'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (187, '5ABIF', 'Kolb', 'Dominik'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (188, '5ABIF', 'Krannich', 'Philipp'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (189, '5ABIF', 'Kurz', 'Manuel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (190, '5ABIF', 'Mairinger', 'Manuel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (191, '5ABIF', 'Pahole', 'Christian'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (192, '5ABIF', 'Rudlstorfer', 'Simon'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (193, '5ABIF', 'Samhaber', 'Stefan'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (194, '5ABIF', 'Schütz', 'Lukas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (195, '5ABIF', 'Sedrakjan', 'Artjom'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (196, '5ABIF', 'Sieber', 'Rene'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (197, '7ABIF', 'Bachinger', 'Daniel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (198, '7ABIF', 'Dujmovic', 'Richard'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (199, '7ABIF', 'Eder', 'Michael'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (200, '7ABIF', 'Fartacek', 'Tobias'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (201, '7ABIF', 'Franzen', 'Dietmar'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (202, '7ABIF', 'Helmberger', 'Florian'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (203, '7ABIF', 'Krump', 'Manuel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (204, '7ABIF', 'Lehner', 'Sebastian'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (205, '7ABIF', 'Leuko', 'Marc'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (206, '7ABIF', 'Oberauer', 'Andreas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (207, '7ABIF', 'Ringer', 'Thomas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (208, '7ABIF', 'Sachsenhofer', 'Philip'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (209, '7ABIF', 'Seering', 'Tim'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (210, '7ABIF', 'Stöhr', 'Markus'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (211, '7ABIF', 'Suchy', 'Mario'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (212, '7ABIF', 'Thumfart', 'Michael'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (213, '7ABIF', 'Weissacher', 'Michael'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (214, '3AKIF', 'Felsch', 'Patrick'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (215, '3AKIF', 'Gessmann', 'Richard'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (216, '3AKIF', 'Haj Salem', 'Maher'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (217, '3AKIF', 'Haller', 'Philipp'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (218, '3AKIF', 'Miskovic', 'Kristijan'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (219, '3AKIF', 'Neuheimer', 'Claudia'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (220, '3AKIF', 'Rammelmüller', 'Manuela'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (221, '3AKIF', 'Redl', 'Jan-Erik'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (222, '3AKIF', 'Stögmüller', 'Martin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (223, '3AKIF', 'Walchetseder', 'Richard'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (224, '3AKIF', 'Zinnecker', 'Andreas'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (225, '5AKIF', 'Beutl', 'Gabriel'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (226, '5AKIF', 'Gruber', 'Siegfried'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (227, '5AKIF', 'Kero', 'Maid'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (228, '5AKIF', 'Schuller', 'Felix'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (229, '7AKIF', 'Kerbl', 'Patrick'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (230, '7AKIF', 'Kletsch', 'Martin'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (231, '7AKIF', 'Leonhartsberger', 'Stefan'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (232, '7AKIF', 'Mayerbäuerl', 'Florian'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (233, '7AKIF', 'Odabas', 'Osman'); 
insert into Schueler(id, KLasse, LastName, FirstName) values (234, '7AKIF', 'Roither', 'Gerald'); 